### ISSUE TITLE
Add only-file and only-dir support

### ISSUE THREAD

**Issue by mawni** [jprichardson/node-klaw#12]
Would you like to have `only file` and `only directory` functionalities?

That is, providing convenient functions to emit `only files` and `only directories` (excluding the root path) by piping a simple [PassThrough](https://nodejs.org/api/stream.html#stream_class_stream_passthrough) stream to the `walk` function, or any other preferred approach?

**Comment by jprichardson** [comment]
Are you thinking this makes things a little more explicit or adds more clarity as opposed to just checking the stats?

**Comment by mawni** [comment]
Well, `klaw` does its job pretty well. I was thinking maybe `klaw` itself also provides convenient functions for the cases when users want to deal with `only-file` or `only-directory` operations as apposed to them have to download other _through_ modules to achieve similar functionalities.

**Comment by jprichardson** [comment]
> download other through modules to achieve similar functionalities.

But why?

```js
var klaw = require('klaw')

var items = [] // files, directories, symlinks, etc
klaw('/some/dir')
  .on('data', function ({ path, stats }) {
    if (stats.isDirectory()) {
      console.log(`${path} is a directory.`)
    } else if (stats.isFile()) {
      console.log(`${path} is file.`)
    }
  })
```

No extra module needed?

Maybe an update to the README would suffice?

**Comment by mawni** [comment]
I know, that's right. I thought that'd be a little more appealing to new users, but it seems like it is not necessary. I like the above example though. That's clearly shows how easy it is to get each separately if it is needed.
 
> Maybe an update to the README would suffice?

I definitely agree with that.

So, maybe we should close this?

**Comment by jprichardson** [comment]
> So, maybe we should close this?

👍
