### ISSUE TITLE
API to stop walking

### ISSUE THREAD

**Issue by targos** [jprichardson/node-klaw#13]
I am using `klaw` to find files but I need to be able to stop walking the directories after a certain limit. I don't think there is currently an official way to do this. Here is my workaround:
```js
function getFilesToProcess(directory, maxElements) {
    return new Promise((resolve, reject) => {
        const items = [];
        const walkStream = fs.walk(directory, {queueMethod: 'pop'});
        walkStream.close = function () {
            this.paths = [];
        };
        walkStream
            .on('data', function (item) => {
                if (item.stats.isFile()) {
                    items.push(item.path);
                    if (maxElements > 0 && items.length >= maxElements) {
                        this.close();
                    }
                }
            })
            .on('end', () => resolve(items))
            .on('error', function (err) {
                this.close();
                reject(err);
            });
    });
}
```

I don't like to have to rely on an implementation detail to achieve this. What do you think about making an official `close` method ?

**Comment by jprichardson** [comment]
Would using `on('readable')` and `read()` and only call `read()` up until `maxElements` solve your problem? See "Streams 2 & 3 (pull) Example" in the README for more info.

**Comment by targos** [comment]
Thanks. I found two ways to deal with my use case:

* Streams 1: call `this.pause()` in the `data` listener
* Streams 2 & 3: stop calling `this.read()` as you suggested

I think the overall effect is the same. There is one thing to keep in mind though: the stream will not always emit the `end` event (and I don't think there is a way to force it to?), so I have to resolve my Promise in two places.
