### ISSUE TITLE
Memory Usage

### ISSUE THREAD

**Issue by DomVinyard** [jprichardson/node-klaw#14]
Does this module scale, if I have a directory with millions (or tens of millions) of files, will this scale elegantly as it iterates or does it have to read the entire directory into memory?

**Comment by jprichardson** [comment]
https://github.com/jprichardson/node-fs-extra/issues/329#issuecomment-269915644

**Comment by DomVinyard** [comment]
```self.fs.readdir(pathItem, function (err, pathItems) {```

This is the problem, the module is loading all of the entries into memory and streaming them out one by one, which means that millions of files will still balloon into a memory overload nightmare.

**Comment by jprichardson** [comment]
> This is the problem, the module is loading all of the entries into memory and streaming them out one by one, which means that millions of files will still balloon into a memory overload nightmare. readdir = unscalable.

Sorry, I assumed that when you stated that a directory has 1M entries, that you meant the directory and it's subdirectory contain a total of 1M entries (the entire tree), not the directory itself has 1M child entries. That is an edge case that very few will encounter and one that we won't currently be optimizing for.

**Comment by DomVinyard** [comment]
Agreed, it's a pretty niche case, thanks for your input
