### ISSUE TITLE
Docs link is broken

### ISSUE THREAD

**Issue by KevinMongiello** [jprichardson/node-klaw#19]
This link is broken:

> If you're not sure of the differences on Node.js streams 1, 2, 3 then I'd recommend this resource as a good starting point: https://strongloop.com/strongblog/whats-new-io-js-beta-streams3/.

**Comment by RyanZim** [comment]
Thanks for reporting @KevinMongiello 

@jprichardson Do you have a good alternate resource?

**Comment by jprichardson** [comment]
> @jprichardson Do you have a good alternate resource?

Nope.
