### ISSUE TITLE
Remove graceful-fs try-catch because of performance

### ISSUE THREAD

**Issue by trustedtomato** [jprichardson/node-klaw#20]
There is an fs option on walk's options object, so the try-catch graceful-fs is unnecessary.
The main problem with it its performance overhead: with it, the library's loading time is around 20ms, and without it its 3ms in avarage.

Would you accept a PR?

**Comment by RyanZim** [comment]
I'm not in favor of this; walking directories has heavy demands on the filesystem and `graceful-fs` is very convenient for helping with this.

If anything, I'd add graceful-fs as a regular dependency and require it without a `try/catch`.

CC: @jprichardson

**Comment by trustedtomato** [comment]
That would radically reduce the loading time too. I ran it a few times and its between 2ms and 5ms which is way better than 20ms.

**Comment by RyanZim** [comment]
OK, SGTM, though I won't merge anything like this without @jprichardson's consent.

**Comment by trustedtomato** [comment]
PR: #21

**Comment by trustedtomato** [comment]
PR was merged; I'll close the issue.
