### ISSUE TITLE
Create LICENSE file

### ISSUE THREAD

**Issue by jaredsmith** [jprichardson/node-klaw#3]
Would you please add a LICENSE file to your packages which includes your copyright information and the text of the MIT license?  The MIT license states that the license text must accompany the source code.  This also makes it easier for people like myself to package up your modules for Linux distributions.

**Comment by jprichardson** [comment]
> The MIT license states that the license text must accompany the source code. 

Sorry, I wasn't aware of this requirement. Done. https://github.com/jprichardson/node-klaw/commit/19a3bf2a9af86cc536d8c58b0f1fe71a91b36465
