### ISSUE TITLE
Feature request: Async/await compatibility!

### ISSUE THREAD

**Issue by quinton-ashley** [jprichardson/node-klaw#30]
It would be great if klaw could be compatible with async/await like fs-extra is.  For now I am using klaw-sync.

**Comment by gamelaster** [comment]
Good idea! But, you don't need to use klaw-sync, just wrap it into Promise:
```js
new Promise((resolve, reject) => {
      let items = []
      klaw('/some/dir')
        .on('data', item => items.push(item.path))
        .on('end', () => resolve(items))
        .on('error', (err, item) => reject(err, item))
    })
```

**Comment by quinton-ashley** [comment]
thanks! I didn't know you could do that!

Here's how to use the Promise in a function for anyone else that wants to see how it can be used:
```
	const klaw = function(dir) {
		return new Promise((resolve, reject) => {
			let items = [];
			let i = 0;
			require('klaw')(dir)
				.on('data', item => {
					if (i > 0) {
						items.push(item.path);
					}
					i++;
				})
				.on('end', () => resolve(items))
				.on('error', (err, item) => reject(err, item));
		});
	};

	await klaw(dir);
```

**Comment by gamelaster** [comment]
Great! I wanted to do that too, but I didn't had that much time! Thanks.
Anyway, I think the developers could implement directly async and promise support to this library.
(I'm too busy at the moment to do it)

**Comment by ad-m** [comment]
See #34 how klaw can be compatible with async-await: 

```
const main = async () => {
    for await (const file of klaw(''/some/dir'')){
       console.log(file);
    }
}
```
Please note that in this way we do not collect information on all paths in memory, but only process as much as necessary.

**Comment by Richie765** [comment]
I think this is the easiest way:

```javascript
const { once } = require('events');

const items = [];
await once(
  klaw('/some/dir').on('data', item => items.push(item.path)),
  'end'
);
console.log(items); 
```

To implement this directly in klaw, I'd suggest a syntax like:
```javascript
await klaw('/some/dir')
  .on('data', item => items.push(item.path))
  .toPromise();
```

See: https://nodejs.org/api/events.html#events_events_once_emitter_name

**Comment by RyanZim** [comment]
Can use an `await`/`for..of` loop, other than that, I'm going to call this a wontfix. klaw is based on streams, which are event-based, not promise-based.
