### ISSUE TITLE
Document that symlinks not traversed

### ISSUE THREAD

**Issue by IgnoredAmbience** [jprichardson/node-klaw#4]
Spent a while trying to work out why my directory tree wasn't being traversed -- my root path was a symlink which isn't traversed.
It would be helpful to document explicitly that symlinks aren't traversed, or provide an option to permit this.

**Comment by jprichardson** [comment]
This is an excellent point. It should allow for this. I'd accept a PR doing so.

**Comment by jprichardson** [comment]
PS, sorry that you had these issues :(

**Comment by jprichardson** [comment]
Actually, I'm not sure why you had this problem.... https://github.com/jprichardson/node-klaw/blob/9d5a5b71a8f1bd872212cff31a6281cd82378450/src/index.js#L27 It's used `lstat` from the beginning. Unless I'm misunderstanding the problem?

**Comment by edgemaster** [comment]
`lstat` doesn't traverse links:
> lstat() is identical to stat(), except that if path is a symbolic link, then the link itself is stat-ed, not the file that it refers to
Swapping `lstat` for `stat` should work, unless there's some other reason for not doing so?

**Comment by piyush-banknovo** [comment]
Symblinks are still not being traversed.

**Comment by WingGao** [comment]
Symblinks are still not being traversed. +1
