### ISSUE TITLE
preserveSymlinks not following links

### ISSUE THREAD

**Issue by TotallyInformation** [jprichardson/node-klaw#42]
* OS: Windows 10
* Node.js v14.15.0
* Klaw version: 3.0.0

Klaw is not actually following symlinks at least on Windows.

If I include a symlink in the `srcFolder` structure, the link is only return as a symlink and is not traversed.

Example code:

```
        const folders = []
        const files = []
        const links = []

        klaw(srcFolder, {'preserveSymlinks': true})
            .on('data', item => {
                if (item.stats.isDirectory()) {
                    folders.push( item.path )
                } else if ( item.stats.isSymbolicLink() )  {
                    links.push( item.path )
                } else if (item.stats.isFile()) {
                    files.push( item.path )
                }
            })
            .on('end', () => {
                console.log({folders, files, links})
            })
```

**Comment by RyanZim** [comment]
Sorry for the slow response here. `klaw` is working as intended. `preserveSymlinks: true` will return the symlink itself instead of following it, the default behavior (without `preserveSymlinks` set) is to follow symlinks.
