### ISSUE TITLE
What does queueMethod do?

### ISSUE THREAD

**Issue by Simran-B** [jprichardson/node-klaw#5]
There's `shift` and `pop`, but how does it change the behavior?

**Comment by jprichardson** [comment]
If you think about the results of a `readdir()`, returns entries sorted A-Za-z, so `pop()` would start at the end, and `shift()` at the beginning. The intent was to configure a DFS vs BFS style search, however, practically that's not the case.

Does that make sense?

**Comment by Simran-B** [comment]
Yeah, thanks!
